# Chaoyuan Dataset Configuration
# =================================
# 超远场景车辆/行人/车窗检测数据集
# 适用任务: detect

path: /media/yun/de2a43ce-446c-4a62-99b3-8ddc6ea1ef87/datasets/ok  # 数据集根目录路径 (相对路径或绝对路径)

train: images/train
val: images/val  # 验证集图像目录 (相对于path)

names:  # 类别名称映射 {class_id: class_name}
  0: car
  1: person
  2: sidewindow
