# Chaoyuan Dataset Configuration
# ==============================
# path: relative to project root or absolute path
path: /media/yun/de2a43ce-446c-4a62-99b3-8ddc6ea1ef87/datasets/chaoyuan

train: images/train
val: images/val
# test: images/test

names:
  0: car
  1: person
  2: sidewindow
